// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    ContentPannel: typeof import('./src/components/ContentPannel.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    FormLabel: typeof import('./src/components/FormLabel.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    ListBox: typeof import('./src/components/ListBox.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    PageHead: typeof import('./src/components/PageHead.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TableItem: typeof import('./src/components/TableItem.vue')['default']
    Help: typeof import('./src/components/header/Help.vue')['default']
    Languages: typeof import('./src/components/header/Languages.vue')['default']
    Notifications: typeof import('./src/components/header/Notifications.vue')['default']
    SearchModal: typeof import('./src/components/header/SearchModal.vue')['default']
    UserMenu: typeof import('./src/components/header/UserMenu.vue')['default']
  }
}

export { }
